### ISSUE TITLE
Does the software actually clean up WinSxs?

### ISSUE THREAD

**Issue by Neuropathy1** [rainxh11/WinSxS_Cleaner#3]
I see that the code only compresses the WinSxs file without cleaning it up. How does it clean up the WinSxs space？

**Comment by rainxh11** [comment]
**Short Answer: NO.**
it doesn't delete anything; it just creates a cleaned-up version in a zip file.
I opted for not deleting files, because of how messy and error prone is dealing with WinSxS permissions, unlocking files used by processes.
the user is responsible of replacing their WinSxS target with the cleaned up one.

**Comment by ibay770** [comment]
Is it possible to make one that does delete files and perhaps run it with Trusted installer permissions to take control of the file?
